[#-- @ftlvariable name="repository" type="com.atlassian.labs.bamboo.git.GitRepositoryPlugin" --]
[@ui.bambooSection]
[@ww.textfield label='Repository URL' name='repository.github-git.repositoryUrl' required='true' /]
[@ww.textfield label='Remote branch' name='repository.github-git.remoteBranch' required='true' /]

[@ui.bambooSection titleKey='repository.advanced.option']
[@ww.checkbox labelKey='repository.advanced.option.enable' toggle='true' name='temporary.github-git.advanced' value='${repository.isAdvancedOptionEnabled(buildConfiguration)?string}' /]
[@ui.bambooSection dependsOn='temporary.github-git.advanced' showOn='true']
    [@ww.checkbox labelKey='repository.common.quietPeriod.enabled' toggle='true' name='repository.github-git.quietPeriod.enabled' /]
    [@ui.bambooSection dependsOn='repository.github-git.quietPeriod.enabled' showOn='true']
        [@ww.textfield labelKey='repository.common.quietPeriod.period' name='repository.github-git.quietPeriod.period' required='true' /]
        [@ww.textfield labelKey='repository.common.quietPeriod.maxRetries' name='repository.github-git.quietPeriod.maxRetries' required='true' /]
    [/@ui.bambooSection]
[/@ui.bambooSection]
[/@ui.bambooSection]
[/@ui.bambooSection]
